[build]
  base = "frontend"
  publish = "build" # CRA genera build/
  command = "npm ci && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  Cache-Control = "no-cache"
